# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('core', '0002_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('booking_mode', models.CharField(choices=[('INSTANT', 'Réservation directe'), ('ON_REQUEST', 'Sur demande')], default='ON_REQUEST', max_length=10, verbose_name='mode de réservation')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3, verbose_name='devise')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('scope', models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], db_index=True, max_length=15, verbose_name='portée')),
                ('is_custom', models.BooleanField(default=False, verbose_name='circuit sur mesure')),
                ('duration_days', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='durée (jours)')),
                ('min_travelers', models.PositiveSmallIntegerField(default=1, verbose_name='voyageurs minimum')),
                ('max_travelers', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='voyageurs maximum')),
                ('departure_points', models.TextField(blank=True, verbose_name='points de départ')),
                ('departure_points_fr', models.TextField(blank=True, null=True, verbose_name='points de départ')),
                ('departure_points_en', models.TextField(blank=True, null=True, verbose_name='points de départ')),
                ('transport_info', models.TextField(blank=True, verbose_name='transport')),
                ('transport_info_fr', models.TextField(blank=True, null=True, verbose_name='transport')),
                ('transport_info_en', models.TextField(blank=True, null=True, verbose_name='transport')),
                ('accommodation_info', models.TextField(blank=True, verbose_name='hébergement')),
                ('accommodation_info_fr', models.TextField(blank=True, null=True, verbose_name='hébergement')),
                ('accommodation_info_en', models.TextField(blank=True, null=True, verbose_name='hébergement')),
                ('inclusions', models.TextField(blank=True)),
                ('inclusions_fr', models.TextField(blank=True, null=True)),
                ('inclusions_en', models.TextField(blank=True, null=True)),
                ('exclusions', models.TextField(blank=True)),
                ('exclusions_fr', models.TextField(blank=True, null=True)),
                ('exclusions_en', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('conditions_fr', models.TextField(blank=True, null=True)),
                ('conditions_en', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('activities', models.ManyToManyField(blank=True, related_name='tours', to='activities.activity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tours', to='destinations.destination')),
                ('theme', models.ForeignKey(blank=True, limit_choices_to={'kind': 'TOUR_THEME'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='core.category')),
            ],
            options={
                'verbose_name': 'circuit',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TourDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='jour')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='tours.tour')),
            ],
            options={
                'verbose_name': 'jour de programme',
                'ordering': ['tour', 'day_number'],
            },
        ),
        migrations.CreateModel(
            name='TourDeparture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='date de départ')),
                ('end_date', models.DateField(verbose_name='date de retour')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='places')),
                ('seats_reserved', models.PositiveIntegerField(default=0, verbose_name='places réservées')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix spécifique')),
                ('status', models.CharField(choices=[('OPEN', 'Ouvert'), ('FULL', 'Complet'), ('CANCELLED', 'Annulé')], default='OPEN', max_length=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tour')),
            ],
            options={
                'verbose_name': 'départ',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tours.tour')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('duration_days__gte', 1)), name='tour_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='tour',
            constraint=models.CheckConstraint(condition=models.Q(('max_travelers__isnull', True), ('max_travelers__gte', models.F('min_travelers')), _connector='OR'), name='tour_max_travelers_gte_min'),
        ),
        migrations.AddConstraint(
            model_name='tourday',
            constraint=models.UniqueConstraint(fields=('tour', 'day_number'), name='unique_tour_day'),
        ),
        migrations.AddIndex(
            model_name='tourdeparture',
            index=models.Index(fields=['start_date', 'status'], name='tours_tourd_start_d_75914b_idx'),
        ),
        migrations.AddConstraint(
            model_name='tourdeparture',
            constraint=models.CheckConstraint(condition=models.Q(('seats_reserved__lte', models.F('capacity'))), name='departure_not_overbooked'),
        ),
        migrations.AddConstraint(
            model_name='tourdeparture',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='departure_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='tourdeparture',
            constraint=models.UniqueConstraint(fields=('tour', 'start_date'), name='unique_departure_per_day'),
        ),
    ]
