# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Extension btree_gist, requise par bookingitem_vehicle_no_overlap.
        ('core', '0001_postgres_extensions'),
        ('accommodations', '0001_initial'),
        ('activities', '0001_initial'),
        ('inquiries', '0001_initial'),
        ('tours', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='référence')),
                ('contact_name', models.CharField(max_length=200, verbose_name='nom du contact')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='email du contact')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='téléphone du contact')),
                ('status', models.CharField(choices=[('REQUESTED', 'Demande reçue'), ('PENDING', 'En attente de confirmation'), ('CONFIRMED', 'Confirmée'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée'), ('REJECTED', 'Refusée'), ('EXPIRED', 'Expirée')], db_index=True, default='REQUESTED', max_length=10, verbose_name='statut')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
                ('customer_comments', models.TextField(blank=True, verbose_name='commentaires du client')),
                ('internal_notes', models.TextField(blank=True, verbose_name='notes internes')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant total')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='inquiries.quoterequest', verbose_name="devis d'origine")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'réservation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix unitaire')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantité')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total ligne')),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin (exclue)')),
                ('pickup_location', models.CharField(blank=True, max_length=200, verbose_name='lieu de prise en charge')),
                ('dropoff_location', models.CharField(blank=True, max_length=200, verbose_name='lieu de restitution')),
                ('is_blocking', models.BooleanField(default=False, editable=False, verbose_name='bloque le stock')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='activities.activity')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bookings.booking')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='accommodations.residence')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='accommodations.room')),
                ('tour_departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='tours.tourdeparture')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'ligne de réservation',
                'verbose_name_plural': 'lignes de réservation',
                'ordering': ['booking', 'start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['-created_at'], name='bookings_bo_created_7d6386_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['expires_at'], name='booking_pending_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('room__isnull', False), ('tour_departure__isnull', False), _negated=True), models.Q(('residence__isnull', False), ('tour_departure__isnull', False), _negated=True), models.Q(('tour_departure__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('tour_departure__isnull', False), _negated=True), models.Q(('residence__isnull', False), ('room__isnull', False), _negated=True), models.Q(('room__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('room__isnull', False), _negated=True), models.Q(('residence__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('residence__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('tour_departure__isnull', False), ('room__isnull', False), ('residence__isnull', False), ('vehicle__isnull', False), ('activity__isnull', False), _connector='OR')), name='bookingitem_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='bookingitem_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 1)), name='bookingitem_quantity_min_1'),
        ),
        migrations.AddConstraint(
            model_name='bookingitem',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_blocking', True), ('vehicle__isnull', False)), expressions=[('vehicle', '='), (apps.core.db.DateRange('start_date', 'end_date', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&')], name='bookingitem_vehicle_no_overlap'),
        ),
    ]
