# Generated by Django 5.2.17 on 2026-09-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('QUOTE_CREATED', 'Nouvelle demande de devis'), ('QUOTE_ACCEPTED', 'Devis accepté par le client'), ('BOOKING_REQUESTED', 'Nouvelle demande de réservation'), ('BOOKING_CANCELLED', 'Réservation annulée'), ('CONTACT_RECEIVED', 'Nouveau message de contact'), ('REVIEW_SUBMITTED', 'Nouvel avis à modérer')], max_length=20, verbose_name='événement')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='lien')),
                ('is_read', models.BooleanField(default=False, verbose_name='lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
