# Generated by Django 5.2.17 on 2026-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.CharField(choices=[('QUOTE_CREATED', 'Nouvelle demande de devis'), ('QUOTE_ACCEPTED', 'Devis accepté par le client'), ('QUOTE_DECLINED', 'Devis refusé par le client'), ('BOOKING_REQUESTED', 'Nouvelle demande de réservation'), ('BOOKING_CANCELLED', 'Réservation annulée'), ('BOOKING_EXPIRED', 'Réservation expirée'), ('CONTACT_RECEIVED', 'Nouveau message de contact'), ('REVIEW_SUBMITTED', 'Nouvel avis à modérer')], max_length=20, verbose_name='événement'),
        ),
    ]
