# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('excerpt', models.CharField(max_length=400, verbose_name='résumé')),
                ('excerpt_fr', models.CharField(max_length=400, null=True, verbose_name='résumé')),
                ('excerpt_en', models.CharField(max_length=400, null=True, verbose_name='résumé')),
                ('content', models.TextField(verbose_name='contenu')),
                ('content_fr', models.TextField(null=True, verbose_name='contenu')),
                ('content_en', models.TextField(null=True, verbose_name='contenu')),
                ('seo_title', models.CharField(blank=True, max_length=70, verbose_name='titre SEO')),
                ('seo_title_fr', models.CharField(blank=True, max_length=70, null=True, verbose_name='titre SEO')),
                ('seo_title_en', models.CharField(blank=True, max_length=70, null=True, verbose_name='titre SEO')),
                ('seo_description', models.CharField(blank=True, max_length=160, verbose_name='description SEO')),
                ('seo_description_fr', models.CharField(blank=True, max_length=160, null=True, verbose_name='description SEO')),
                ('seo_description_en', models.CharField(blank=True, max_length=160, null=True, verbose_name='description SEO')),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIE', 'Publié')], db_index=True, default='BROUILLON', max_length=10, verbose_name='statut')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='publié le')),
                ('reading_time', models.PositiveSmallIntegerField(default=1, editable=False, verbose_name='temps de lecture (min)')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'BLOG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.category', verbose_name='catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='core.tag')),
            ],
            options={
                'verbose_name': 'article',
                'ordering': ['-published_at', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('status', 'PUBLIE'), _negated=True), ('published_at__isnull', False), _connector='OR'), name='blogpost_published_has_date')],
            },
        ),
    ]
