# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=100, null=True, unique=True, verbose_name='nom')),
                ('name_en', models.CharField(max_length=100, null=True, unique=True, verbose_name='nom')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône (Lucide)')),
                ('scope', models.CharField(choices=[('HOTEL', 'Hôtels'), ('RESIDENCE', 'Résidences'), ('BOTH', 'Les deux')], default='BOTH', max_length=10)),
            ],
            options={
                'verbose_name': 'équipement',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('accommodation_type', models.CharField(choices=[('HOTEL', 'Hôtel'), ('APARTMENT', 'Appartement'), ('PARTNER', 'Hébergement partenaire')], default='HOTEL', max_length=10, verbose_name='type')),
                ('stars', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='étoiles')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('amenities', models.ManyToManyField(blank=True, related_name='hotels', to='accommodations.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotels', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'hôtel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.hotel')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('booking_mode', models.CharField(choices=[('INSTANT', 'Réservation directe'), ('ON_REQUEST', 'Sur demande')], default='ON_REQUEST', max_length=10, verbose_name='mode de réservation')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3, verbose_name='devise')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('rooms_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='nombre de chambres')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacité')),
                ('services', models.TextField(blank=True)),
                ('services_fr', models.TextField(blank=True, null=True)),
                ('services_en', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('conditions_fr', models.TextField(blank=True, null=True)),
                ('conditions_en', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('amenities', models.ManyToManyField(blank=True, related_name='residences', to='accommodations.amenity')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residences', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'résidence',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.residence')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_mode', models.CharField(choices=[('INSTANT', 'Réservation directe'), ('ON_REQUEST', 'Sur demande')], default='ON_REQUEST', max_length=10, verbose_name='mode de réservation')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3, verbose_name='devise')),
                ('name', models.CharField(max_length=150, verbose_name='type de chambre')),
                ('name_fr', models.CharField(max_length=150, null=True, verbose_name='type de chambre')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='type de chambre')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='capacité')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='nombre de chambres')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodations.hotel')),
            ],
            options={
                'verbose_name': 'chambre',
                'ordering': ['hotel', 'base_price'],
            },
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(condition=models.Q(('stars__isnull', True), models.Q(('stars__gte', 1), ('stars__lte', 5)), _connector='OR'), name='hotel_stars_1_to_5'),
        ),
    ]
