# Generated by Django 5.2.17 on 2026-09-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('title', models.CharField(max_length=150, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=150, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icône (Lucide)')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('quote_service_type', models.CharField(blank=True, choices=[('VOL', "Billet d'avion"), ('HEBERGEMENT', 'Hébergement'), ('CIRCUIT', 'Circuit / excursion'), ('VISA', 'Visa et formalités'), ('ASSURANCE', 'Assurance voyage'), ('TRANSPORT', 'Transport'), ('LOCATION_VEHICULE', 'Location de véhicule'), ('ACTIVITES', 'Activités'), ('EVENEMENT', "Organisation d'événement"), ('CONSEIL', 'Conseil et planification')], max_length=20, verbose_name='prestation pré-cochée dans le devis')),
            ],
            options={
                'verbose_name': 'service',
                'ordering': ['order', 'title'],
            },
        ),
    ]
