# Generated by Django 5.2.17 on 2026-09-25 15:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150, verbose_name='libellé')),
                ('label_fr', models.CharField(max_length=150, null=True, verbose_name='libellé')),
                ('label_en', models.CharField(max_length=150, null=True, verbose_name='libellé')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('unit', models.CharField(blank=True, help_text='Ex. « par personne »', max_length=50, verbose_name='unité')),
                ('unit_fr', models.CharField(blank=True, help_text='Ex. « par personne »', max_length=50, null=True, verbose_name='unité')),
                ('unit_en', models.CharField(blank=True, help_text='Ex. « par personne »', max_length=50, null=True, verbose_name='unité')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='services.service')),
            ],
            options={
                'verbose_name': 'tarif',
                'ordering': ['service', 'order', 'id'],
            },
        ),
    ]
