# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_postgres_extensions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], max_length=3, unique=True, verbose_name='devise')),
                ('rate_from_xof', models.DecimalField(decimal_places=10, max_digits=18, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)], verbose_name='taux depuis XOF')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='mis à jour le')),
            ],
            options={
                'verbose_name': 'taux de change',
                'verbose_name_plural': 'taux de change',
                'ordering': ['currency'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency_name', models.CharField(default='Impact Voyage', max_length=150, verbose_name="nom de l'agence")),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('slogan_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('slogan_en', models.CharField(blank=True, max_length=200, null=True)),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='sous-titre du hero')),
                ('hero_subtitle_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='sous-titre du hero')),
                ('hero_subtitle_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='sous-titre du hero')),
                ('hero_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image du hero')),
                ('hero_video_url', models.URLField(blank=True, verbose_name='vidéo du hero')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('opening_hours', models.TextField(blank=True, verbose_name='horaires')),
                ('opening_hours_fr', models.TextField(blank=True, null=True, verbose_name='horaires')),
                ('opening_hours_en', models.TextField(blank=True, null=True, verbose_name='horaires')),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ex. {"facebook": "https://…", "instagram": "https://…"}', verbose_name='réseaux sociaux')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('about_content', models.TextField(blank=True, verbose_name='contenu « À propos »')),
                ('about_content_fr', models.TextField(blank=True, null=True, verbose_name='contenu « À propos »')),
                ('about_content_en', models.TextField(blank=True, null=True, verbose_name='contenu « À propos »')),
            ],
            options={
                'verbose_name': 'paramètres du site',
                'verbose_name_plural': 'paramètres du site',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=60, null=True, verbose_name='nom')),
                ('name_en', models.CharField(max_length=60, null=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=100, null=True, verbose_name='nom')),
                ('name_en', models.CharField(max_length=100, null=True, verbose_name='nom')),
                ('slug', models.SlugField(max_length=120)),
                ('kind', models.CharField(choices=[('TOUR_THEME', 'Thème de circuit'), ('ACTIVITY', 'Activité'), ('BLOG', 'Blog'), ('MEDIA', 'Médiathèque')], db_index=True, max_length=20, verbose_name='type')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
            ],
            options={
                'verbose_name': 'catégorie',
                'ordering': ['kind', 'order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'slug'), name='unique_category_slug_per_kind')],
            },
        ),
    ]
