# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('category', models.CharField(choices=[('VOYAGE_GROUPE', 'Voyage de groupe'), ('EXCURSION', 'Excursion'), ('PROFESSIONNEL', 'Événement professionnel'), ('CULTUREL', 'Événement culturel'), ('SPORTIF', 'Événement sportif'), ('TOURISTIQUE', 'Événement touristique'), ('PRIVE', 'Événement privé'), ('AUTRE', 'Autre')], db_index=True, max_length=15, verbose_name='catégorie')),
                ('date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('location', models.CharField(max_length=200, verbose_name='lieu')),
                ('location_fr', models.CharField(max_length=200, null=True, verbose_name='lieu')),
                ('location_en', models.CharField(max_length=200, null=True, verbose_name='lieu')),
                ('participants_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='participants')),
                ('partners', models.JSONField(blank=True, default=list, help_text='Ex. [{"name": "…", "logo": "https://…", "url": "https://…"}]', verbose_name='partenaires')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'événement',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo')], default='PHOTO', max_length=5)),
                ('image', models.ImageField(blank=True, height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('video_url', models.URLField(blank=True, verbose_name='lien vidéo')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
            options={
                'verbose_name': "média d'événement",
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('date')), _connector='OR'), name='event_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='eventimage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('type', 'PHOTO'), models.Q(('image', ''), _negated=True)), models.Q(('type', 'VIDEO'), models.Q(('video_url', ''), _negated=True)), _connector='OR'), name='events_eventimage_photo_or_video'),
        ),
    ]
