# Generated by Django 5.2.17 on 2026-09-25 13:44

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
        ('offers', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='objet')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('NOUVEAU', 'Nouveau'), ('LU', 'Lu'), ('TRAITE', 'Traité'), ('ARCHIVE', 'Archivé')], db_index=True, default='NOUVEAU', max_length=10, verbose_name='statut')),
            ],
            options={
                'verbose_name': 'message de contact',
                'verbose_name_plural': 'messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference', models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='référence')),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30, verbose_name='téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('country_code', models.CharField(blank=True, max_length=2, verbose_name='pays de résidence (ISO 3166-1)')),
                ('destination_text', models.CharField(blank=True, max_length=200, verbose_name='destination souhaitée')),
                ('date_departure', models.DateField(blank=True, null=True, verbose_name='date de départ')),
                ('date_return', models.DateField(blank=True, null=True, verbose_name='date de retour')),
                ('adults', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='adultes')),
                ('children', models.PositiveSmallIntegerField(default=0, verbose_name='enfants')),
                ('travel_type', models.CharField(blank=True, choices=[('LOISIRS', 'Loisirs'), ('AFFAIRES', 'Affaires'), ('FAMILLE', 'Famille'), ('LUNE_DE_MIEL', 'Lune de miel'), ('GROUPE', 'Groupe'), ('PELERINAGE', 'Pèlerinage'), ('ETUDES', 'Études'), ('AUTRE', 'Autre')], max_length=15, verbose_name='type de voyage')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('accommodation_pref', models.CharField(blank=True, max_length=200, verbose_name='hébergement souhaité')),
                ('transport_pref', models.CharField(blank=True, max_length=200, verbose_name='transport')),
                ('services_requested', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('VOL', "Billet d'avion"), ('HEBERGEMENT', 'Hébergement'), ('CIRCUIT', 'Circuit / excursion'), ('VISA', 'Visa et formalités'), ('ASSURANCE', 'Assurance voyage'), ('TRANSPORT', 'Transport'), ('LOCATION_VEHICULE', 'Location de véhicule'), ('ACTIVITES', 'Activités'), ('EVENEMENT', "Organisation d'événement"), ('CONSEIL', 'Conseil et planification')], max_length=20), blank=True, default=list, size=None, verbose_name='services demandés')),
                ('comments', models.TextField(blank=True, verbose_name='commentaires')),
                ('proposal_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant proposé')),
                ('proposal_message', models.TextField(blank=True, verbose_name='proposition')),
                ('proposal_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='proposition envoyée le')),
                ('proposal_valid_until', models.DateField(blank=True, null=True, verbose_name="proposition valable jusqu'au")),
                ('language', models.CharField(default='fr', max_length=5, verbose_name='langue')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='consentement donné le')),
                ('status', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours'), ('DEVIS_ENVOYE', 'Devis envoyé'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('TERMINEE', 'Terminée')], db_index=True, default='NOUVELLE', max_length=15, verbose_name='statut')),
                ('activities', models.ManyToManyField(blank=True, related_name='quote_requests', to='activities.activity')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotes', to=settings.AUTH_USER_MODEL, verbose_name='commercial assigné')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='destinations.destination')),
                ('source_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='offers.offer')),
                ('source_tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tours.tour')),
            ],
            options={
                'verbose_name': 'demande de devis',
                'verbose_name_plural': 'demandes de devis',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inquiries_q_created_c94407_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_departure__isnull', True), ('date_return__isnull', True), ('date_return__gte', models.F('date_departure')), _connector='OR'), name='quote_return_after_departure'), models.CheckConstraint(condition=models.Q(('adults__gte', 1)), name='quote_at_least_one_adult')],
            },
        ),
    ]
