# Generated by Django 5.2.17 on 2026-09-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='language',
            field=models.CharField(default='fr', max_length=5, verbose_name='langue'),
        ),
    ]
