# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('booking_mode', models.CharField(choices=[('INSTANT', 'Réservation directe'), ('ON_REQUEST', 'Sur demande')], default='ON_REQUEST', max_length=10, verbose_name='mode de réservation')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3, verbose_name='devise')),
                ('brand', models.CharField(max_length=60, verbose_name='marque')),
                ('model', models.CharField(max_length=60, verbose_name='modèle')),
                ('category', models.CharField(choices=[('ECONOMIQUE', 'Économique'), ('BERLINE', 'Berline'), ('SUV', 'SUV'), ('4X4', '4x4'), ('MINIBUS', 'Minibus'), ('LUXE', 'Luxe'), ('UTILITAIRE', 'Utilitaire')], db_index=True, max_length=12, verbose_name='catégorie')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1990)], verbose_name='année')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='immatriculation')),
                ('seats', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='places')),
                ('transmission', models.CharField(choices=[('MANUELLE', 'Manuelle'), ('AUTOMATIQUE', 'Automatique')], max_length=12, verbose_name='boîte')),
                ('fuel', models.CharField(choices=[('ESSENCE', 'Essence'), ('DIESEL', 'Diesel'), ('HYBRIDE', 'Hybride'), ('ELECTRIQUE', 'Électrique')], max_length=10, verbose_name='carburant')),
                ('air_conditioning', models.BooleanField(default=True, verbose_name='climatisation')),
                ('features', models.JSONField(blank=True, default=list, help_text='Ex. ["GPS", "Bluetooth"]', verbose_name='caractéristiques')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'véhicule',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
