# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('events', '0001_initial'),
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='couverture')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='date de publication')),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'MEDIA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_albums', to='core.category')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='events.event')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='tours.tour')),
            ],
            options={
                'verbose_name': 'album',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PHOTO', 'Photo'), ('VIDEO', 'Vidéo')], default='PHOTO', max_length=5)),
                ('image', models.ImageField(blank=True, height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('video_url', models.URLField(blank=True, verbose_name='lien vidéo')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('title_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='légende')),
                ('title_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='légende')),
                ('is_featured', models.BooleanField(default=False, verbose_name='mise en avant')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='media.mediaalbum')),
            ],
            options={
                'verbose_name': 'média',
                'ordering': ['order', 'id'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type', 'PHOTO'), models.Q(('image', ''), _negated=True)), models.Q(('type', 'VIDEO'), models.Q(('video_url', ''), _negated=True)), _connector='OR'), name='media_mediaitem_photo_or_video')],
            },
        ),
    ]
