# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('name', models.CharField(max_length=150, verbose_name='nom')),
                ('name_fr', models.CharField(max_length=150, null=True, verbose_name='nom')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='nom')),
                ('continent', models.CharField(choices=[('AFRIQUE', 'Afrique'), ('EUROPE', 'Europe'), ('AMERIQUES', 'Amériques'), ('ASIE', 'Asie'), ('MOYEN_ORIENT', 'Moyen-Orient'), ('OCEANIE', 'Océanie')], db_index=True, max_length=20)),
                ('country_code', models.CharField(db_index=True, max_length=2, verbose_name='pays (ISO 3166-1)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ville')),
                ('city_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='ville')),
                ('city_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='ville')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('best_period', models.CharField(blank=True, max_length=200, verbose_name='meilleure période')),
                ('best_period_fr', models.CharField(blank=True, max_length=200, null=True, verbose_name='meilleure période')),
                ('best_period_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='meilleure période')),
                ('attractions', models.TextField(blank=True, help_text='Une attraction par ligne.')),
                ('attractions_fr', models.TextField(blank=True, help_text='Une attraction par ligne.', null=True)),
                ('attractions_en', models.TextField(blank=True, help_text='Une attraction par ligne.', null=True)),
                ('tips', models.TextField(blank=True, verbose_name='conseils')),
                ('tips_fr', models.TextField(blank=True, null=True, verbose_name='conseils')),
                ('tips_en', models.TextField(blank=True, null=True, verbose_name='conseils')),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('tags', models.ManyToManyField(blank=True, related_name='destinations', to='core.tag')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='destinations.destination')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
