# Generated by Django 5.2.17 on 2026-09-30 08:43

import apps.core.files
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880), apps.core.validators.validate_image_content], verbose_name='image principale'),
        ),
        migrations.AlterField(
            model_name='destinationimage',
            name='image',
            field=models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880), apps.core.validators.validate_image_content], width_field='width'),
        ),
    ]
