# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('booking_mode', models.CharField(choices=[('INSTANT', 'Réservation directe'), ('ON_REQUEST', 'Sur demande')], default='ON_REQUEST', max_length=10, verbose_name='mode de réservation')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix de base')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3, verbose_name='devise')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField()),
                ('description_fr', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('duration_hours', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='durée (heures)')),
                ('max_participants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False, verbose_name='mise en avant')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('category', models.ForeignKey(blank=True, limit_choices_to={'kind': 'ACTIVITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='core.category')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'activité',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='height', upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], width_field='width')),
                ('width', models.PositiveIntegerField(editable=False, null=True)),
                ('height', models.PositiveIntegerField(editable=False, null=True)),
                ('alt_text', models.CharField(max_length=255, verbose_name='texte alternatif')),
                ('alt_text_fr', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('alt_text_en', models.CharField(max_length=255, null=True, verbose_name='texte alternatif')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='activities.activity')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='activity',
            constraint=models.CheckConstraint(condition=models.Q(('duration_hours__gt', 0)), name='activity_duration_positive'),
        ),
    ]
