# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(max_length=150, verbose_name='nom')),
                ('author_email', models.EmailField(max_length=254, verbose_name='email (non publié)')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='note')),
                ('comment', models.TextField(verbose_name='commentaire')),
                ('photo', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)])),
                ('is_featured', models.BooleanField(default=False, verbose_name="afficher sur l'accueil")),
                ('status', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVE', 'Approuvé'), ('REFUSE', 'Refusé')], db_index=True, default='EN_ATTENTE', max_length=10, verbose_name='statut')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='activities.activity')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='destinations.destination')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accommodations.hotel')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'avis',
                'verbose_name_plural': 'avis',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_1_to_5'), models.CheckConstraint(condition=models.Q(models.Q(('destination__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('destination__isnull', False), ('hotel__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('destination__isnull', False), _negated=True), models.Q(('hotel__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('hotel__isnull', False), _negated=True)), name='review_at_most_one_target')],
            },
        ),
    ]
