# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('transport_type', models.CharField(choices=[('TRANSFERT_AEROPORT', 'Transfert aéroport'), ('BUS', 'Bus'), ('NAVETTE', 'Navette'), ('FERRY', 'Bateau / ferry'), ('TRAIN', 'Train'), ('CHAUFFEUR', 'Véhicule avec chauffeur')], db_index=True, max_length=20, verbose_name='type de transport')),
                ('origin', models.CharField(max_length=150, verbose_name='origine')),
                ('destination', models.CharField(max_length=150)),
                ('max_passengers', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='passagers maximum')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix à partir de')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('schedule_info', models.TextField(blank=True, verbose_name='horaires / fréquence')),
                ('schedule_info_fr', models.TextField(blank=True, null=True, verbose_name='horaires / fréquence')),
                ('schedule_info_en', models.TextField(blank=True, null=True, verbose_name='horaires / fréquence')),
            ],
            options={
                'verbose_name': 'service de transport',
                'verbose_name_plural': 'services de transport',
                'ordering': ['transport_type', 'origin'],
            },
        ),
    ]
