# Generated by Django 5.2.17 on 2026-09-25 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisaService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='publié')),
                ('destination_country_code', models.CharField(db_index=True, max_length=2, verbose_name='pays de destination (ISO 3166-1)')),
                ('country_slug', models.SlugField(max_length=100, verbose_name='slug du pays')),
                ('nationality_code', models.CharField(db_index=True, max_length=2, verbose_name='nationalité (ISO 3166-1)')),
                ('visa_type', models.CharField(max_length=100, verbose_name='type de visa')),
                ('visa_type_fr', models.CharField(max_length=100, null=True, verbose_name='type de visa')),
                ('visa_type_en', models.CharField(max_length=100, null=True, verbose_name='type de visa')),
                ('purpose', models.CharField(choices=[('TOURISME', 'Tourisme'), ('AFFAIRES', 'Affaires'), ('ETUDES', 'Études'), ('FAMILLE', 'Visite familiale'), ('TRANSIT', 'Transit'), ('AUTRE', 'Autre')], max_length=10, verbose_name='motif')),
                ('validity_duration', models.CharField(blank=True, max_length=100, verbose_name='durée de validité')),
                ('validity_duration_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='durée de validité')),
                ('validity_duration_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='durée de validité')),
                ('processing_time', models.CharField(blank=True, max_length=100, verbose_name='délai de traitement')),
                ('processing_time_fr', models.CharField(blank=True, max_length=100, null=True, verbose_name='délai de traitement')),
                ('processing_time_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='délai de traitement')),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='frais')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('required_documents', models.TextField(blank=True, verbose_name='documents requis')),
                ('required_documents_fr', models.TextField(blank=True, null=True, verbose_name='documents requis')),
                ('required_documents_en', models.TextField(blank=True, null=True, verbose_name='documents requis')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'service visa',
                'verbose_name_plural': 'services visa',
                'ordering': ['country_slug', 'visa_type'],
                'constraints': [models.UniqueConstraint(fields=('destination_country_code', 'nationality_code', 'visa_type', 'purpose'), name='unique_visa_service'), models.UniqueConstraint(fields=('destination_country_code', 'nationality_code', 'visa_type_fr', 'purpose'), name='unique_visa_service-fr'), models.UniqueConstraint(fields=('destination_country_code', 'nationality_code', 'visa_type_en', 'purpose'), name='unique_visa_service-en')],
            },
        ),
    ]
