# Generated by Django 5.2.17 on 2026-09-25 13:44

import apps.core.files
import apps.core.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
        ('tours', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('cover_image', models.ImageField(blank=True, upload_to=apps.core.files.UploadTo(), validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp']), apps.core.validators.MaxFileSizeValidator(5242880)], verbose_name='image principale')),
                ('cover_alt', models.CharField(blank=True, max_length=255, verbose_name='texte alternatif')),
                ('cover_alt_fr', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('cover_alt_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='texte alternatif')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('title_fr', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('title_en', models.CharField(max_length=200, null=True, verbose_name='titre')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='accroche')),
                ('short_description_fr', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('short_description_en', models.CharField(blank=True, max_length=300, null=True, verbose_name='accroche')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True)),
                ('conditions_fr', models.TextField(blank=True, null=True)),
                ('conditions_en', models.TextField(blank=True, null=True)),
                ('offer_type', models.CharField(choices=[('VOYAGE', 'Voyage'), ('HOTEL', 'Hôtel'), ('CIRCUIT', 'Circuit'), ('BILLET', "Billet d'avion"), ('LOCATION', 'Location'), ('PACKAGE', 'Package')], db_index=True, max_length=10, verbose_name='type')),
                ('initial_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix initial')),
                ('promo_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix promotionnel')),
                ('currency', models.CharField(choices=[('XOF', 'Franc CFA (FCFA)'), ('EUR', 'Euro'), ('USD', 'Dollar américain'), ('GBP', 'Livre sterling')], default='XOF', max_length=3)),
                ('start_date', models.DateField(verbose_name='début')),
                ('end_date', models.DateField(verbose_name='fin')),
                ('seats_available', models.PositiveIntegerField(blank=True, null=True, verbose_name='places disponibles')),
                ('badge', models.CharField(blank=True, choices=[('NOUVEAU', 'Nouveau'), ('PROMOTION', 'Promotion'), ('POPULAIRE', 'Populaire'), ('DERNIERES_PLACES', 'Dernières places')], max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='active')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='activities.activity')),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='destinations.destination')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accommodations.hotel')),
                ('residence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accommodations.residence')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tours.tour')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'offre',
                'ordering': ['end_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='offers_offe_start_d_8459ce_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('promo_price__lt', models.F('initial_price'))), name='offer_promo_below_initial'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='offer_end_after_start'), models.CheckConstraint(condition=models.Q(models.Q(('hotel__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('residence__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('tour__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('tour__isnull', False), _negated=True), models.Q(('hotel__isnull', False), ('residence__isnull', False), _negated=True), models.Q(('hotel__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('hotel__isnull', False), _negated=True), models.Q(('residence__isnull', False), ('vehicle__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('residence__isnull', False), _negated=True), models.Q(('activity__isnull', False), ('vehicle__isnull', False), _negated=True)), name='offer_at_most_one_target')],
            },
        ),
    ]
